Noto che la remduration manca praticamente sempre, mentre il resto dei dati sul sonno sono presenti sempre tutti insieme. Trovo un modo per calcolare il punteggio che faccia uso di questi dati.

In [1]:
import pandas as pd

In [2]:
steps = pd.read_csv("../data/dati.csv.gz")[
    ["uuid", "date", "steps", 'sleepduration', 'lightduration',
     'deepduration']]  # Il dataset qui è abbastanza denso, per ora può andare bene eliminare le righe con valori mancanti

In [3]:
def sleep_score(x):
    optimal_light_ratio = .5
    optimal_deep_ratio = .25

    # Penalità sul light sleep X Penalità sul deep sleep X Penalità sulla durata del sonno
    x["sleep_score"] = (1 - abs(x["lightduration"] / x["sleepduration"] - optimal_light_ratio)) * (
            1 - abs(x["deepduration"] / x["sleepduration"] - optimal_deep_ratio)) * (
                               1 - abs(x["sleepduration"] / x["sleepduration"].mean() - 1))
    return x


steps = steps.groupby("uuid").apply(sleep_score, include_groups=False)
steps.sample(100)

,,date,steps,sleepduration,lightduration,deepduration,sleep_score
uuid,,,,,,,
cbaafc481739098887091013283cef8cecfe52a5,1687781,2016-08-17,7102.18,NaN,NaN,NaN,NaN
a1d964e82c76b43998ea38af40e66cf85b474089,1313912,2016-07-19,4740.14,8.05,5.10,2.89,0.727263
54e793db1423c23d53e6af66723954ecb58fc840,632011,2017-01-19,8582.23,8.56,4.18,4.37,0.651407
44245c6fc04c6331c74a95ca92c8dfccefe530b1,484997,2016-06-25,3292.81,6.23,4.05,2.15,0.750533
83116cdd467e5a2bc01067818c3ff163215d2c6a,1033756,2016-05-14,NaN,4.22,2.61,0.92,0.457056
...,...,...,...,...,...,...,...
690b0266e5cf2d04b03d176d9cfa98cc11b354bc,812598,2016-06-21,7872.70,5.04,3.59,1.43,0.559551
f632790525b8dc128c1f060e9884012f6bffc26c,2065945,2016-12-03,10948.27,3.00,1.85,1.14,0.273125
ca567dd566699b683c7b6183dd8879149f23d985,1675832,2016-10-21,4854.02,7.24,2.33,4.90,0.459562
4e7b49b15b3255998667d537d90a233174e1e9bf,573575,2016-05-06,5587.40,8.23,4.58,3.67,0.676290
4e10fee95da1d3447472871358a82284e904dd64,570780,2016-05-24,9594.62,NaN,NaN,NaN,NaN

In [4]:
steps = steps.rename_axis(["uuid", "id"]).reset_index().drop(
    columns=["id"])  # Per un csv più pulito, infatti il groupby aggiunge una colonna che non voglio
steps.head()

,uuid,date,steps,sleepduration,lightduration,deepduration,sleep_score
0,1003e58667235e01b49008155604980b3900b00e,2016-07-31,3049.04,NaN,NaN,NaN,NaN
1,1003e58667235e01b49008155604980b3900b00e,2016-08-01,4309.81,11.31,7.38,3.99,0.547576
2,1003e58667235e01b49008155604980b3900b00e,2016-08-02,255.11,NaN,NaN,NaN,NaN
3,1003e58667235e01b49008155604980b3900b00e,2016-08-03,5118.07,NaN,NaN,NaN,NaN
4,1003e58667235e01b49008155604980b3900b00e,2016-08-04,2228.88,12.90,7.91,4.94,0.415384

Non ho più bisogno degli altri dati, mi tengo solo quelli sui passi e sulla qualità del sonno.

In [5]:
steps[["uuid", "date", "steps", "sleep_score"]].to_csv("../data/valutati.csv.gz", index=False)